### ISSUE TITLE
Code not working. Please help.

### ISSUE THREAD

**Issue by melo1111344** [scifisatan/covidbot#2]
Hi, I contacted you through Twitter as well (Abhi). I tried running this code and it didn't work. It showed me error with keep_alive(). You suggested me to remove that line and without keep_alive(), it shows further more error. I know the bot you created is still working - this means, the code should work (unless this isn't the code you used for the Covidbot). Can you please provide some explanation? If the code hasn't be updated, can you please do that? This will be very helpful. I have been following and working on this for such a long time.

**Comment by scifisatan** [comment]
Hey! Sorry for the late reply but i hope it might be helpful for you. The code has been updated.
